set -g default-terminal "screen-256color"

# Set Ctrl + a as prefix
set -g prefix C-a
unbind C-b
bind-key C-a send-prefix

# Use tmux windows as indexed tabs without creating native macOS tabs
set -g base-index 1
set -g renumber-windows on
bind-key -n M-t new-window -c "#{pane_current_path}"
bind-key -n M-w kill-window
bind-key -n M-1 select-window -t :=1
bind-key -n M-2 select-window -t :=2
bind-key -n M-3 select-window -t :=3
bind-key -n M-4 select-window -t :=4
bind-key -n M-5 select-window -t :=5
bind-key -n M-6 select-window -t :=6
bind-key -n M-7 select-window -t :=7
bind-key -n M-8 select-window -t :=8
bind-key -n M-9 select-window -t :=9

# Split window horizontally with <prefix>|
unbind %
bind | split-window -h

# Split window vertically with <prefix>-
unbind '"'
bind - split-window -v

# Reload tmux config: <prefix>r
unbind r
bind r source-file ~/.config/tmux/tmux.conf

# Resize splits: <prefix>h or j, k, l
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

# Maximize split: <prefix>m
bind -r m resize-pane -Z

# Enable mouse mode
set -g mouse on

# Enable VI[M] mode
set-window-option -g mode-keys vi

# Restore Ctrl + l (clear screen) use <prefix>C-l to clear
bind C-l send-keys 'C-l'

# <prefix>C-k to clear scrollback in terminal
bind C-k clear-history

# Enable copy mode using <prefix>[ and use 'v' to highlight, 'y' to yank
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection

# Allow resizing splits using mouse
unbind -T copy-mode-vi MouseDragEnd1Pane

# Launch new tmux session using <prefix>f
bind-key -r f run-shell "tmux neww ~/.config/tmux/rx/sessionizer.sh"

set -g @plugin 'tmux-plugins/tpm'

# list of plugins
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'jimeh/tmux-themepack'

set -g @themepack 'powerline/default/cyan'

run '~/.tmux/plugins/tpm/tpm'
